### ISSUE TITLE
Errors out when no "references" found

### ISSUE THREAD

**Issue by dpriskorn** [lehinevych/MediaWikiAPI#47]
Please check that the key exist before trying to return it.
```
(edit)	en.wikipedia.org	(!bot)	'Arutperunjothi'
http://en.wikipedia.org/wiki/Arutperunjothi
Downloading wikitext
Download finished
['Cast', 'Soundtrack', 'See also']
Traceback (most recent call last):
  File "/home/egil/src/python/asseeibot/main.py", line 75, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/egil/src/python/asseeibot/main.py", line 58, in main
    links = page.references
  File "/usr/lib/python3.9/site-packages/mediawikiapi/wikipediapage.py", line 324, in references
    self._references = [
  File "/usr/lib/python3.9/site-packages/mediawikiapi/wikipediapage.py", line 324, in <listcomp>
    self._references = [
  File "/usr/lib/python3.9/site-packages/mediawikiapi/wikipediapage.py", line 151, in __continued_query
    for datum in pages[self.pageid][prop]:
KeyError: 'extlinks'

```

**Comment by egils-consulting** [comment]
This seems to fix it
```
modified   mediawikiapi/wikipediapage.py
@@ -148,8 +148,11 @@ class WikipediaPage(object):
                 for datum in pages.values():  # in python 3.3+: "yield from pages.values()"
                     yield datum
             else:
-                for datum in pages[self.pageid][prop]:
-                    yield datum
+                if prop in pages[self.pageid]:
+                    for datum in pages[self.pageid][prop]:
+                        yield datum
+                else:
+                    print(f"Key '{prop}' not found in page")
 
             if 'continue' not in request:
                 break
```
